"use client";

import { useState } from "react";
import Link from "next/link";
import "../product.css";

const FAQS = [
  { q: "What is a disposable polythene drape used for?", a: "A disposable polythene drape is used to surround the area being examined, treated, or operated upon, helping maintain a controlled working space during medical procedures." },
  { q: "Where is a disposable polythene drape placed?", a: "It is placed around the specific area of the body that is being examined or treated to define the working area." },
  { q: "Why are disposable drapes important in medical procedures?", a: "They help create a structured and controlled environment by covering the surrounding area, supporting better organization during procedures." },
  { q: "When are disposable polythene drapes used?", a: "They are used during medical examination, treatment, and surgical procedures where maintaining a focused and controlled area is important." },
  { q: "How does a disposable drape support hygiene?", a: "By surrounding the treatment area, it helps manage exposure and supports cleaner working conditions during procedures." },
];

const APPLICATIONS = [
  { icon: "🏥", title: "Medical Examination", desc: "Surrounds the required area during examination and helps define the working space." },
  { icon: "🩺", title: "Treatment Procedures", desc: "Supports organized preparation around areas being treated in healthcare environments." },
  { icon: "🔬", title: "Surgical Procedures", desc: "Helps maintain a focused and controlled area around the site of a procedure." },
  { icon: "🧼", title: "Healthcare Hygiene", desc: "Provides a practical disposable solution where cleanliness and controlled conditions matter." },
];

const RELATED_PRODUCTS = [
  { id: 1, name: "Disposable Apron", href: "/disposable-section/disposable-aprons", image: "/assests/img/disposable-apron-1-600x630.jpg" },
  { id: 4, name: "Disposable Coverall", href: "/disposable-section/disposable-coverall", image: "/assests/img/disposable-coverall-600x630.jpg" },
  { id: 5, name: "Disposable Face Mask", href: "/disposable-section/disposable-face-mask", image: "/assests/img/disposable-facemask-600x630.jpg" },
  { id: 39, name: "Disposable Surgeon Cap", href: "/disposable-section/disposable-surgeon-cap", image: "/assests/img/Disposable-Surgeon-Cap-600x630.jpg" },
  { id: 40, name: "Disposable Surgeons Gown", href: "/disposable-section/disposable-surgeons-gown", image: "/assests/img/Disposable-Surgeon-Gown-600x630.jpg" },
];

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return <div className="faq-item" onClick={() => setOpen(!open)}><div className="faq-row"><p className="faq-question">{q}</p><span className={`faq-toggle ${open ? "faq-toggle-open" : "faq-toggle-closed"}`}>{open ? "−" : "+"}</span></div>{open && <p className="faq-answer">{a}</p>}</div>;
}

export default function PolytheneDrapePage() {
  return (
    <>
      <header className="hero"><div className="hero-circle-1" /><div className="hero-circle-2" /><div className="hero-circle-3" /><div className="hero-inner fade-in"><div className="hero-content"><span className="hero-badge">Trusted Manufacturer &amp; Supplier · India</span><h1 className="hero-title">Disposable Polythene Drape<br /><em>Manufacturer in India</em></h1><p className="hero-desc">Crown Healthcare Disposables is a trusted Disposable Polythene Drape Manufacturer in India offering high-quality drapes for medical examination, treatment, and surgical procedures. Reliable disposable drape supplier for healthcare applications.</p><div className="hero-btns"><Link href="/disposable-section" className="btn-primary">Explore Products →</Link><Link href="/contact" className="btn-outline">Request Quote</Link></div></div><div className="hero-img-wrap"><img src="/assests/img/Disposable-Polythene-Drape-600x630.jpg" alt="Disposable Polythene Drape" className="hero-img" /></div></div></header>

      <div className="intro-strip"><div className="intro-inner">{["Medical Examination", "Treatment Support", "Surgical Use", "Controlled Conditions"].map(txt => <span key={txt} className="intro-item"><span className="intro-check">✔</span> {txt}</span>)}</div></div>

      <section id="overview" className="section"><div className="two-col"><div><p className="overview-label">About Our Products</p><h2 className="overview-heading">Disposable Polythene Drape</h2><p className="overview-text">Crown Healthcare Disposables is a trusted disposable polythene drape manufacturer in India, offering protective solutions designed for use in medical environments. A disposable polythene drape is placed around the area to be examined, treated, or operated upon, helping maintain controlled conditions during medical procedures.</p><p className="overview-text-last">In healthcare settings, maintaining a defined and clean working area is essential. Disposable polythene drapes support this by covering and surrounding the required area, helping manage exposure during examination and treatment.</p></div><div className="stats-box">{[{ num: "Medical", label: "Examination" }, { num: "Treatment", label: "Support" }, { num: "Surgical", label: "Use" }, { num: "Clean", label: "Working Area" }].map(({ num, label }) => <div key={label} className="stat-card"><p className="stat-num">{num}</p><p className="stat-label">{label}</p></div>)}</div></div></section>

      <section className="products-section"><div className="products-inner"><p className="section-label">Understanding the Product</p><h2 className="section-heading">What is a Disposable Polythene Drape and Why is it Used?</h2><div className="product-card card-hover"><div className="product-card-body"><p className="product-card-desc">A disposable polythene drape is used to cover and surround specific areas of the body during medical examination, treatment, or surgical procedures. Its purpose is to create a controlled working space where the focus area is clearly defined.</p><p className="product-card-desc">By being placed around the area being treated, the drape helps support hygiene practices and maintain a structured environment during procedures. This makes it an important part of routine medical preparation where controlled conditions are required.</p></div></div></div></section>

      <section className="features-section"><div className="features-inner"><p className="features-label">Product Highlights</p><h2 className="features-heading">Key Features of Disposable Polythene Drape</h2><p className="overview-text" style={{ textAlign: "center", maxWidth: "800px", margin: "0 auto 3rem" }}>The disposable polythene drape is designed to be positioned around areas that require examination or treatment. Its use helps define the working space, making procedures more organized and controlled.</p><div className="three-col">{[{ icon: "🛡️", title: "Defined Working Area", desc: "Helps clearly surround the area being examined, treated, or operated upon." }, { icon: "🏥", title: "Medical Use", desc: "Designed for routine use in healthcare and medical procedure environments." }, { icon: "🩺", title: "Treatment Support", desc: "Supports organized preparation around the focus area during treatment." }, { icon: "🔬", title: "Surgical Application", desc: "Suitable for surgical procedures where controlled conditions are required." }, { icon: "🧼", title: "Hygiene Focused", desc: "Supports cleaner working conditions during examination and treatment." }, { icon: "♻️", title: "Disposable Design", desc: "Single-use design is practical for procedures requiring regular replacement." }].map(f => <div key={f.title} className="feature-card"><span className="feature-icon">{f.icon}</span><h3 className="feature-title">{f.title}</h3><p className="feature-desc">{f.desc}</p></div>)}</div></div></section>

      <section id="applications" className="applications-section"><div className="applications-inner"><p className="section-label">Where It&apos;s Used</p><h2 className="section-heading">Applications of Disposable Polythene Drape</h2><p className="overview-text" style={{ textAlign: "center", maxWidth: "800px", margin: "0 auto 3rem" }}>Disposable polythene drapes are used in medical environments during examination, treatment, and surgical procedures. They are placed around the area being worked on to support controlled conditions and maintain a focused treatment space.</p><div className="four-col">{APPLICATIONS.map(app => <div key={app.title} className="app-card card-hover"><span className="app-icon">{app.icon}</span><h3 className="app-title">{app.title}</h3><p className="app-desc">{app.desc}</p></div>)}</div></div></section>

      <section className="section"><div className="two-col"><div><p className="overview-label">Medical Procedures</p><h2 className="overview-heading">Importance of Disposable Drapes in Medical Procedures</h2><p className="overview-text">In medical procedures, maintaining a controlled and organized environment is essential. Disposable polythene drapes help achieve this by surrounding the treatment area, allowing healthcare professionals to focus on the procedure.</p><p className="overview-text-last">Their use supports better handling of the working area and contributes to maintaining cleanliness during examination and treatment processes.</p></div><div className="stats-box">{[{ num: "Focused", label: "Treatment Area" }, { num: "Controlled", label: "Conditions" }, { num: "Organized", label: "Preparation" }, { num: "Reliable", label: "Protection" }].map(({ num, label }) => <div key={label} className="stat-card"><p className="stat-num">{num}</p><p className="stat-label">{label}</p></div>)}</div></div></section>

      <section className="supplier-section"><div className="supplier-inner"><div><p className="supplier-label">Supplier in India</p><h2 className="supplier-heading">Disposable Polythene Drape Supplier in India</h2><p className="supplier-text">Crown Healthcare Disposables is a dependable disposable polythene drape manufacturer and supplier in India, supporting healthcare environments with essential disposable protective products. We aim to meet the growing demand for products used in examination and treatment procedures where maintaining controlled conditions is necessary.</p><p className="supplier-text-last">As a disposable drape supplier, we focus on reliability, consistency, and products that fit routine healthcare usage.</p></div><div id="contact" className="contact-card"><h3 className="contact-title">Request a Quote</h3><div className="form-fields">{["Your Name", "Company / Organisation", "Email Address", "Phone Number"].map(ph => <input key={ph} placeholder={ph} className="form-input" />)}<textarea placeholder="Your Requirements" className="form-input" rows="3" /><button className="form-btn">Submit Enquiry →</button></div></div></div></section>

      <section className="products-section"><div className="products-inner"><p className="section-label">Our Commitment</p><h2 className="section-heading">Why Choose Crown Healthcare Disposables</h2><div className="product-card card-hover"><div className="product-card-body"><p className="product-card-desc">Choosing the right disposable polythene drape manufacturer in India is important for healthcare providers that rely on consistent and reliable protective products. Crown Healthcare Disposables focuses on offering practical solutions that support real medical needs.</p><p className="product-card-desc">As a disposable drape supplier, our focus is on reliability, consistency, and supporting customers with products that fit routine healthcare usage.</p></div></div></div></section>

      <section id="faqs" className="faqs-section"><div className="faqs-inner"><p className="faqs-label">Got Questions?</p><h2 className="faqs-heading">Frequently Asked Questions</h2><div>{FAQS.map(faq => <FAQItem key={faq.q} {...faq} />)}</div></div></section>

      <section className="related-section"><div className="related-inner"><h2 className="related-heading">Related Products</h2><div className="related-scroll">{RELATED_PRODUCTS.map(product => <Link key={product.id} href={product.href} className="related-card-link"><div className="related-card"><div className="related-card-img"><img src={product.image} alt={product.name} className="related-img" /></div><div className="related-card-info"><h3 className="related-card-name">{product.name}</h3><span className="related-card-btn">View More</span></div></div></Link>)}</div></div></section>
    </>
  );
}
