"use client";

import { useState } from "react";
import Link from "next/link";
import "../product.css";

const FAQS = [
  { q: "What is a PPE kit used for?", a: "A PPE kit is used to provide protection in environments where exposure to contaminants or external risks may occur, helping support safety and hygiene." },
  { q: "Who uses PPE kits?", a: "PPE kits are used by professionals in medical, industrial, and frontline environments where protective clothing is required." },
  { q: "Why are PPE kits important?", a: "They help reduce exposure to risks and support controlled working conditions, making them essential for maintaining safety and hygiene." },
  { q: "Where are PPE kits commonly used?", a: "They are commonly used in healthcare facilities, industrial workplaces, and frontline operations." },
  { q: "What industries require PPE kits?", a: "PPE kits are used in industries where safety, hygiene, and protection are critical to daily operations." },
  { q: "Why choose a reliable PPE kit manufacturer?", a: "A reliable manufacturer ensures consistent supply and dependable protective solutions, which are essential for maintaining safety standards." },
];

const APPLICATIONS = [
  { icon: "🏥", title: "Medical Use", desc: "Supports infection control and hygiene practices in hospitals, clinics, and healthcare facilities." },
  { icon: "🏭", title: "Industrial Workplaces", desc: "Helps protect workers from exposure to external elements in demanding industrial conditions." },
  { icon: "🛡️", title: "Frontline Operations", desc: "Provides an added layer of safety in frontline environments requiring consistent protection." },
  { icon: "🧼", title: "Safety & Hygiene", desc: "Supports controlled working conditions where cleanliness and protective practices are essential." },
];

const RELATED_PRODUCTS = [
  { id: 1, name: "Disposable Apron", href: "/disposable-section/disposable-aprons", image: "/assests/img/disposable-apron-1-600x630.jpg" },
  { id: 4, name: "Disposable Coverall", href: "/disposable-section/disposable-coverall", image: "/assests/img/disposable-coverall-600x630.jpg" },
  { id: 5, name: "Disposable Face Mask", href: "/disposable-section/disposable-face-mask", image: "/assests/img/disposable-facemask-600x630.jpg" },
  { id: 39, name: "Disposable Surgeon Cap", href: "/disposable-section/disposable-surgeon-cap", image: "/assests/img/Disposable-Surgeon-Cap-600x630.jpg" },
  { id: 42, name: "Disposable Wraparound Gown SMS", href: "/disposable-section/disposable-wraparound-gown", image: "/assests/img/wraparound-gown-sms-1-600x630.jpg" },
];

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return <div className="faq-item" onClick={() => setOpen(!open)}><div className="faq-row"><p className="faq-question">{q}</p><span className={`faq-toggle ${open ? "faq-toggle-open" : "faq-toggle-closed"}`}>{open ? "−" : "+"}</span></div>{open && <p className="faq-answer">{a}</p>}</div>;
}

export default function PpeKitPage() {
  return (
    <>
      <header className="hero"><div className="hero-circle-1" /><div className="hero-circle-2" /><div className="hero-circle-3" /><div className="hero-inner fade-in"><div className="hero-content"><span className="hero-badge">Trusted Manufacturer &amp; Supplier · India</span><h1 className="hero-title">PPE Kit<br /><em>Manufacturer in India</em></h1><p className="hero-desc">Crown Healthcare Disposables is a PPE Kit Manufacturer in India, supplying quality protective kits for medical, industrial, and frontline use.</p><div className="hero-btns"><Link href="/disposable-section" className="btn-primary">Explore Products →</Link><Link href="/contact" className="btn-outline">Request Quote</Link></div></div><div className="hero-img-wrap"><img src="/assests/img/Manufacturer of PPE Kit.jpeg" alt="PPE Kit" className="hero-img" /></div></div></header>

      <div className="intro-strip"><div className="intro-inner">{["Medical Protection", "Industrial Use", "Frontline Safety", "Hygiene Support"].map(txt => <span key={txt} className="intro-item"><span className="intro-check">✔</span> {txt}</span>)}</div></div>

      <section id="overview" className="section"><div className="two-col"><div><p className="overview-label">About Our Products</p><h2 className="overview-heading">PPE Kit</h2><p className="overview-text">Crown Healthcare Disposables is a trusted PPE kit manufacturer in India, specializing in high-quality protective clothing designed for safety and hygiene. Our PPE kits are developed to support environments where protection, cleanliness, and controlled conditions are essential.</p><p className="overview-text-last">As a reliable manufacturer, we supply PPE solutions for medical, industrial, and frontline use, helping organizations maintain safety standards in demanding working conditions.</p></div><div className="stats-box">{[{ num: "Medical", label: "Protection" }, { num: "Industrial", label: "Use" }, { num: "Frontline", label: "Safety" }, { num: "India", label: "Wide Supply" }].map(({ num, label }) => <div key={label} className="stat-card"><p className="stat-num">{num}</p><p className="stat-label">{label}</p></div>)}</div></div></section>

      <section className="products-section"><div className="products-inner"><p className="section-label">Understanding the Product</p><h2 className="section-heading">What is a PPE Kit and Why is it Important?</h2><div className="product-card card-hover"><div className="product-card-body"><p className="product-card-desc">A PPE kit (Personal Protective Equipment kit) is a set of protective clothing used to safeguard individuals in environments where exposure to contaminants or external risks may occur. PPE kits are widely used in healthcare, industrial, and frontline settings to support safety and hygiene practices.</p><p className="product-card-desc">Their importance lies in providing a protective layer that helps reduce exposure and supports controlled working conditions. In high-risk environments, PPE kits play a critical role in maintaining safety for both individuals and surroundings.</p></div></div></div></section>

      <section className="products-section"><div className="products-inner"><p className="section-label">Multi-Industry Protection</p><h2 className="section-heading">PPE Kits for Medical, Industrial, and Frontline Use</h2><div className="product-card card-hover"><div className="product-card-body"><p className="product-card-desc">PPE kits are used across multiple sectors where protection and hygiene are essential. In medical environments, they are used to support infection control practices. In industrial settings, they help protect workers from exposure to external elements.</p><p className="product-card-desc">For frontline use, PPE kits provide an added layer of safety in situations that require consistent protective measures. Our focus is on delivering solutions that meet the needs of these diverse environments.</p></div></div></div></section>

      <section className="features-section"><div className="features-inner"><p className="features-label">Product Highlights</p><h2 className="features-heading">Key Features of PPE Kits</h2><p className="overview-text" style={{ textAlign: "center", maxWidth: "800px", margin: "0 auto 3rem" }}>Our PPE kits are designed with a focus on safety and hygiene, making them suitable for environments where protection is required. They are developed as protective clothing solutions intended to support consistent use in demanding conditions.</p><div className="three-col">{[{ icon: "🛡️", title: "Protective Layer", desc: "Helps reduce exposure to contaminants and external risks in demanding environments." }, { icon: "🏥", title: "Medical Ready", desc: "Supports hygiene and infection control practices in healthcare facilities." }, { icon: "🏭", title: "Industrial Use", desc: "Designed for workplaces where workers need protection from external elements." }, { icon: "🧑‍🚒", title: "Frontline Safety", desc: "Provides added protection in frontline operations and critical settings." }, { icon: "🧼", title: "Hygiene Focused", desc: "Supports controlled working conditions where cleanliness is essential." }, { icon: "♻️", title: "Practical Design", desc: "Protective clothing solution intended for consistent operational use." }].map(f => <div key={f.title} className="feature-card"><span className="feature-icon">{f.icon}</span><h3 className="feature-title">{f.title}</h3><p className="feature-desc">{f.desc}</p></div>)}</div></div></section>

      <section id="applications" className="applications-section"><div className="applications-inner"><p className="section-label">Where It&apos;s Used</p><h2 className="section-heading">Applications of PPE Kits</h2><p className="overview-text" style={{ textAlign: "center", maxWidth: "800px", margin: "0 auto 3rem" }}>PPE kits are widely used in healthcare facilities, industrial workplaces, and frontline operations where maintaining safety and hygiene is critical. They are an essential part of protective practices in environments where exposure to risks needs to be minimized.</p><div className="four-col">{APPLICATIONS.map(app => <div key={app.title} className="app-card card-hover"><span className="app-icon">{app.icon}</span><h3 className="app-title">{app.title}</h3><p className="app-desc">{app.desc}</p></div>)}</div></div></section>

      <section className="section"><div className="two-col"><div><p className="overview-label">Safety &amp; Hygiene</p><h2 className="overview-heading">Why PPE Kits Are Essential for Safety and Hygiene</h2><p className="overview-text">In environments where safety and hygiene cannot be compromised, PPE kits serve as a critical layer of protection. They help reduce exposure to external risks and support controlled conditions during operations.</p><p className="overview-text-last">Their use is especially important in situations where maintaining cleanliness and safety directly impacts outcomes, making them a key component of protective equipment across industries.</p></div><div className="stats-box">{[{ num: "Safety", label: "Support" }, { num: "Hygiene", label: "Control" }, { num: "Risk", label: "Reduction" }, { num: "Reliable", label: "Protection" }].map(({ num, label }) => <div key={label} className="stat-card"><p className="stat-num">{num}</p><p className="stat-label">{label}</p></div>)}</div></div></section>

      <section className="supplier-section"><div className="supplier-inner"><div><p className="supplier-label">Supplier in India</p><h2 className="supplier-heading">PPE Kit Supplier in India</h2><p className="supplier-text">Crown Healthcare Disposables is a dependable PPE kit manufacturer and supplier in India, supporting organizations with high-quality protective clothing solutions. We aim to meet the growing demand for PPE kits used in environments where safety, hygiene, and protection are essential.</p><p className="supplier-text-last">As a PPE kit supplier, we understand the importance of consistency, usability, and dependable supply. Our approach is centered on providing protective solutions that align with safety requirements.</p></div><div id="contact" className="contact-card"><h3 className="contact-title">Request a Quote</h3><div className="form-fields">{["Your Name", "Company / Organisation", "Email Address", "Phone Number"].map(ph => <input key={ph} placeholder={ph} className="form-input" />)}<textarea placeholder="Your Requirements" className="form-input" rows="3" /><button className="form-btn">Submit Enquiry →</button></div></div></div></section>

      <section className="products-section"><div className="products-inner"><p className="section-label">Our Commitment</p><h2 className="section-heading">Why Choose Crown Healthcare Disposables</h2><div className="product-card card-hover"><div className="product-card-body"><p className="product-card-desc">Choosing the right PPE kit manufacturer in India is important for businesses and institutions that depend on consistent protective solutions. Crown Healthcare Disposables focuses on delivering reliable PPE kits designed to support real-world usage across medical, industrial, and frontline environments.</p><p className="product-card-desc">We provide protective solutions that align with safety requirements and help organizations maintain hygiene standards.</p></div></div></div></section>

      <section id="faqs" className="faqs-section"><div className="faqs-inner"><p className="faqs-label">Got Questions?</p><h2 className="faqs-heading">Frequently Asked Questions</h2><div>{FAQS.map(faq => <FAQItem key={faq.q} {...faq} />)}</div></div></section>

      <section className="related-section"><div className="related-inner"><h2 className="related-heading">Related Products</h2><div className="related-scroll">{RELATED_PRODUCTS.map(product => <Link key={product.id} href={product.href} className="related-card-link"><div className="related-card"><div className="related-card-img"><img src={product.image} alt={product.name} className="related-img" /></div><div className="related-card-info"><h3 className="related-card-name">{product.name}</h3><span className="related-card-btn">View More</span></div></div></Link>)}</div></div></section>
    </>
  );
}
