"use client";

import { useState } from "react";
import Link from "next/link";
import "../product.css";

const FAQS = [
  { q: "What is a disposable wraparound gown SMS used for?", a: "A disposable wraparound gown SMS is used during major surgeries to provide protection for the surgeon and support controlled surgical conditions." },
  { q: "Why is a wraparound gown important in major surgeries?", a: "It helps provide protection during procedures, allowing the surgeon to operate in a controlled and hygienic environment." },
  { q: "Who uses disposable wraparound gowns?", a: "Disposable wraparound gowns are worn by surgeons during surgical procedures, especially major surgeries." },
  { q: "When should a disposable wraparound gown SMS be used?", a: "It should be used during major surgical procedures where protection and hygiene are essential." },
  { q: "How does a wraparound gown support surgical safety?", a: "By providing protection during surgery, it helps maintain controlled conditions and supports safe surgical practices." },
  { q: "What makes wraparound gowns suitable for surgical use?", a: "Their design and purpose are focused on providing protection during procedures, making them suitable for use in major surgeries." },
];

const APPLICATIONS = [
  { icon: "🏥", title: "Major Surgeries", desc: "Provides protective clothing for surgeons during complex and major surgical procedures." },
  { icon: "🩺", title: "Operating Rooms", desc: "Supports controlled and hygienic conditions in operating room environments." },
  { icon: "👨‍⚕️", title: "Surgeon Protection", desc: "Worn by surgeons as part of standard protective wear during operations." },
  { icon: "🧼", title: "Surgical Hygiene", desc: "Helps maintain consistent protective practices where hygiene is critical." },
];

const RELATED_PRODUCTS = [
  { id: 1, name: "Disposable Apron", href: "/disposable-section/disposable-aprons", image: "/assests/img/disposable-apron-1-600x630.jpg" },
  { id: 4, name: "Disposable Coverall", href: "/disposable-section/disposable-coverall", image: "/assests/img/disposable-coverall-600x630.jpg" },
  { id: 5, name: "Disposable Face Mask", href: "/disposable-section/disposable-face-mask", image: "/assests/img/disposable-facemask-600x630.jpg" },
  { id: 39, name: "Disposable Surgeon Cap", href: "/disposable-section/disposable-surgeon-cap", image: "/assests/img/Disposable-Surgeon-Cap-600x630.jpg" },
  { id: 40, name: "Disposable Surgeons Gown", href: "/disposable-section/disposable-surgeons-gown", image: "/assests/img/Disposable-Surgeon-Gown-600x630.jpg" },
];

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return <div className="faq-item" onClick={() => setOpen(!open)}><div className="faq-row"><p className="faq-question">{q}</p><span className={`faq-toggle ${open ? "faq-toggle-open" : "faq-toggle-closed"}`}>{open ? "−" : "+"}</span></div>{open && <p className="faq-answer">{a}</p>}</div>;
}

export default function DisposableWraparoundGownPage() {
  return (
    <>
      <header className="hero"><div className="hero-circle-1" /><div className="hero-circle-2" /><div className="hero-circle-3" /><div className="hero-inner fade-in"><div className="hero-content"><span className="hero-badge">Trusted Manufacturer &amp; Supplier · India</span><h1 className="hero-title">Disposable Wraparound Gown SMS<br /><em>Manufacturer in India</em></h1><p className="hero-desc">Crown Healthcare Disposables is a Disposable Wraparound Gown SMS Manufacturer in India, supplying quality gowns for major surgeries and surgical hygiene.</p><div className="hero-btns"><Link href="/disposable-section" className="btn-primary">Explore Products →</Link><Link href="/contact" className="btn-outline">Request Quote</Link></div></div><div className="hero-img-wrap"><img src="/assests/img/wraparound-gown-sms-1-600x630.jpg" alt="Disposable Wraparound Gown SMS" className="hero-img" /></div></div></header>

      <div className="intro-strip"><div className="intro-inner">{["Major Surgery Use", "Surgeon Protection", "Surgical Hygiene", "Controlled Conditions"].map(txt => <span key={txt} className="intro-item"><span className="intro-check">✔</span> {txt}</span>)}</div></div>

      <section id="overview" className="section"><div className="two-col"><div><p className="overview-label">About Our Products</p><h2 className="overview-heading">Disposable Wraparound Gown SMS</h2><p className="overview-text">Crown Healthcare Disposables is a trusted disposable wraparound gown SMS manufacturer in India, offering protective clothing designed for surgical environments. A disposable wraparound gown SMS is worn by surgeons during major surgeries to provide protection and support controlled conditions.</p><p className="overview-text-last">In critical surgical procedures, maintaining protection and minimizing risk is essential. Disposable wraparound gowns play an important role in helping ensure that surgeons are protected during operations, contributing to safer and more controlled surgical environments.</p></div><div className="stats-box">{[{ num: "Major", label: "Surgery Use" }, { num: "Surgeon", label: "Protection" }, { num: "SMS", label: "Gown Material" }, { num: "India", label: "Wide Supply" }].map(({ num, label }) => <div key={label} className="stat-card"><p className="stat-num">{num}</p><p className="stat-label">{label}</p></div>)}</div></div></section>

      <section className="products-section"><div className="products-inner"><p className="section-label">Understanding the Product</p><h2 className="section-heading">What is a Disposable Wraparound Gown SMS and Why is it Used?</h2><div className="product-card card-hover"><div className="product-card-body"><p className="product-card-desc">A disposable wraparound gown SMS is a protective garment used during major surgeries. It is worn by surgeons to provide protection while performing procedures in environments where hygiene and control are essential.</p><p className="product-card-desc">Its purpose is to support safe surgical practices by helping create a protective barrier during operations. In major surgeries, where precision and controlled conditions are critical, such protective clothing becomes an important part of standard surgical preparation.</p></div></div></div></section>

      <section className="products-section"><div className="products-inner"><p className="section-label">Major Surgery Protection</p><h2 className="section-heading">Role of Wraparound Gowns in Major Surgeries</h2><div className="product-card card-hover"><div className="product-card-body"><p className="product-card-desc">During major surgical procedures, maintaining protection for the surgeon is essential. A disposable wraparound gown SMS helps support this by offering coverage that contributes to a controlled working environment.</p><p className="product-card-desc">Its use helps ensure that protective measures are consistently followed during surgery, allowing the surgical team to focus on the procedure while maintaining hygiene standards.</p></div></div></div></section>

      <section className="features-section"><div className="features-inner"><p className="features-label">Product Highlights</p><h2 className="features-heading">Key Functional Benefits of Disposable Wraparound Gown SMS</h2><p className="overview-text" style={{ textAlign: "center", maxWidth: "800px", margin: "0 auto 3rem", color: "rgba(255, 255, 255, 0.9)" }}>The disposable wraparound gown SMS is designed to provide protection during surgical procedures. Its role is centered around supporting the surgeon by helping reduce exposure during operations.</p><div className="three-col">{[{ icon: "🛡️", title: "Surgeon Protection", desc: "Provides a protective layer during major surgical procedures." }, { icon: "🏥", title: "Major Surgery Use", desc: "Designed for operating rooms and complex surgical environments." }, { icon: "🩺", title: "Controlled Conditions", desc: "Supports a controlled working environment during operations." }, { icon: "🧼", title: "Surgical Hygiene", desc: "Helps maintain protective practices where cleanliness is essential." }, { icon: "♻️", title: "Disposable Design", desc: "Single-use nature supports consistent hygiene during procedures." }, { icon: "⚡", title: "Practical Use", desc: "Protective clothing designed for routine surgical preparation." }].map(f => <div key={f.title} className="feature-card"><span className="feature-icon">{f.icon}</span><h3 className="feature-title">{f.title}</h3><p className="feature-desc">{f.desc}</p></div>)}</div></div></section>

      <section id="applications" className="applications-section"><div className="applications-inner"><p className="section-label">Where It&apos;s Used</p><h2 className="section-heading">Applications of Disposable Wraparound Gown SMS</h2><p className="overview-text" style={{ textAlign: "center", maxWidth: "800px", margin: "0 auto 3rem" }}>Disposable wraparound gowns are used in surgical environments, particularly during major surgeries where protection and hygiene are critical. They are worn by surgeons as part of standard protective wear to support safe and controlled procedures.</p><div className="four-col">{APPLICATIONS.map(app => <div key={app.title} className="app-card card-hover"><span className="app-icon">{app.icon}</span><h3 className="app-title">{app.title}</h3><p className="app-desc">{app.desc}</p></div>)}</div></div></section>

      <section className="section"><div className="two-col"><div><p className="overview-label">Surgical Safety</p><h2 className="overview-heading">Why Protective Gowns Are Important in Major Surgeries</h2><p className="overview-text">In major surgeries, maintaining protection is directly linked to safety and procedural success. Disposable wraparound gowns help support this by providing a protective layer for the surgeon.</p><p className="overview-text-last">Their use contributes to maintaining controlled surgical conditions and reinforces hygiene practices, making them an essential part of surgical protective equipment.</p></div><div className="stats-box">{[{ num: "Major", label: "Procedures" }, { num: "Surgeon", label: "Safety" }, { num: "Controlled", label: "Conditions" }, { num: "Surgical", label: "Hygiene" }].map(({ num, label }) => <div key={label} className="stat-card"><p className="stat-num">{num}</p><p className="stat-label">{label}</p></div>)}</div></div></section>

      <section className="supplier-section"><div className="supplier-inner"><div><p className="supplier-label">Supplier in India</p><h2 className="supplier-heading">Disposable Wraparound Gown SMS Supplier in India</h2><p className="supplier-text">Crown Healthcare Disposables is a dependable disposable wraparound gown SMS manufacturer and supplier in India, supporting healthcare environments with essential protective clothing. We aim to meet the demand for products used in surgical procedures where maintaining protection and control is critical.</p><p className="supplier-text-last">As a wraparound gown supplier, we focus on consistency, usability, and meeting the needs of environments where protection and hygiene are essential.</p></div><div id="contact" className="contact-card"><h3 className="contact-title">Request a Quote</h3><div className="form-fields">{["Your Name", "Company / Organisation", "Email Address", "Phone Number"].map(ph => <input key={ph} placeholder={ph} className="form-input" />)}<textarea placeholder="Your Requirements" className="form-input" rows="3" /><button className="form-btn">Submit Enquiry →</button></div></div></div></section>

      <section className="products-section"><div className="products-inner"><p className="section-label">Our Commitment</p><h2 className="section-heading">Why Choose Crown Healthcare Disposables</h2><div className="product-card card-hover"><div className="product-card-body"><p className="product-card-desc">Choosing the right disposable wraparound gown SMS manufacturer in India is important for healthcare providers that depend on reliable protective clothing during critical procedures. Crown Healthcare Disposables focuses on delivering products that align with real surgical requirements.</p><p className="product-card-desc">We support healthcare institutions with dependable protective solutions used in major surgeries, with a focus on consistency, usability, and hygiene.</p></div></div></div></section>

      <section id="faqs" className="faqs-section"><div className="faqs-inner"><p className="faqs-label">Got Questions?</p><h2 className="faqs-heading">Frequently Asked Questions</h2><div>{FAQS.map(faq => <FAQItem key={faq.q} {...faq} />)}</div></div></section>

      <section className="related-section"><div className="related-inner"><h2 className="related-heading">Related Products</h2><div className="related-scroll">{RELATED_PRODUCTS.map(product => <Link key={product.id} href={product.href} className="related-card-link"><div className="related-card"><div className="related-card-img"><img src={product.image} alt={product.name} className="related-img" /></div><div className="related-card-info"><h3 className="related-card-name">{product.name}</h3><span className="related-card-btn">View More</span></div></div></Link>)}</div></div></section>
    </>
  );
}
