"use client";

import { useState } from "react";
import Link from "next/link";
import "../product.css";

const FAQS = [
  { q: "What is a disposable surgeons gown used for?", a: "A disposable surgeons gown is used during surgery to help reduce the transfer of germs and support hygiene in medical procedures." },
  { q: "Why is a surgeons gown important in infection control?", a: "It acts as a protective barrier that helps limit the spread of germs, which is essential for maintaining clean and controlled surgical environments." },
  { q: "Who uses disposable surgeons gowns?", a: "Disposable surgeons gowns are worn by surgeons during surgical procedures as part of standard protective practices." },
  { q: "When should a disposable surgeons gown be used?", a: "It should be used during surgeries and medical procedures where maintaining hygiene and preventing contamination is essential." },
  { q: "How does a surgeons gown help maintain a clean surgical environment?", a: "By acting as a barrier, it helps reduce the transfer of germs and supports controlled conditions during surgical procedures." },
];

const APPLICATIONS = [
  { icon: "🏥", title: "Operating Rooms", desc: "Used during surgery to support clean and controlled operating room conditions." },
  { icon: "🩺", title: "Surgical Procedures", desc: "Worn by surgeons as part of standard protective practices during operations." },
  { icon: "🧼", title: "Infection Control", desc: "Helps limit the transfer of germs and supports hygiene in medical procedures." },
  { icon: "👨‍⚕️", title: "Healthcare Facilities", desc: "Suitable for hospitals and healthcare environments where protective clothing is essential." },
];

const RELATED_PRODUCTS = [
  { id: 1, name: "Disposable Apron", href: "/disposable-section/disposable-aprons", image: "/assests/img/disposable-apron-1-600x630.jpg" },
  { id: 4, name: "Disposable Coverall", href: "/disposable-section/disposable-coverall", image: "/assests/img/disposable-coverall-600x630.jpg" },
  { id: 5, name: "Disposable Face Mask", href: "/disposable-section/disposable-face-mask", image: "/assests/img/disposable-facemask-600x630.jpg" },
  { id: 39, name: "Disposable Surgeon Cap", href: "/disposable-section/disposable-surgeon-cap", image: "/assests/img/Disposable-Surgeon-Cap-600x630.jpg" },
  { id: 42, name: "Disposable Wraparound Gown SMS", href: "/disposable-section/disposable-wraparound-gown", image: "/assests/img/wraparound-gown-sms-1-600x630.jpg" },
];

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return <div className="faq-item" onClick={() => setOpen(!open)}><div className="faq-row"><p className="faq-question">{q}</p><span className={`faq-toggle ${open ? "faq-toggle-open" : "faq-toggle-closed"}`}>{open ? "−" : "+"}</span></div>{open && <p className="faq-answer">{a}</p>}</div>;
}

export default function DisposableSurgeonsGownPage() {
  return (
    <>
      <header className="hero"><div className="hero-circle-1" /><div className="hero-circle-2" /><div className="hero-circle-3" /><div className="hero-inner fade-in"><div className="hero-content"><span className="hero-badge">Trusted Manufacturer &amp; Supplier · India</span><h1 className="hero-title">Disposable Surgeons Gown<br /><em>Manufacturer in India</em></h1><p className="hero-desc">Crown Healthcare Disposables is a Disposable Surgeons Gown Manufacturer in India, supplying quality gowns for surgical procedures and healthcare hygiene.</p><div className="hero-btns"><Link href="/disposable-section" className="btn-primary">Explore Products →</Link><Link href="/contact" className="btn-outline">Request Quote</Link></div></div><div className="hero-img-wrap"><img src="/assests/img/Disposable-Surgeon-Gown-600x630.jpg" alt="Disposable Surgeons Gown" className="hero-img" /></div></div></header>

      <div className="intro-strip"><div className="intro-inner">{["Surgical Protection", "Germ Transfer Control", "Operating Room Use", "Healthcare Hygiene"].map(txt => <span key={txt} className="intro-item"><span className="intro-check">✔</span> {txt}</span>)}</div></div>

      <section id="overview" className="section"><div className="two-col"><div><p className="overview-label">About Our Products</p><h2 className="overview-heading">Disposable Surgeons Gown</h2><p className="overview-text">Crown Healthcare Disposables is a dependable disposable surgeons gown manufacturer in India, providing protective clothing used in surgical environments where maintaining hygiene is essential. A disposable surgeons gown is worn by a surgeon during surgery to help avoid the transfer of germs and support controlled working conditions.</p><p className="overview-text-last">In surgical procedures, the environment must remain as clean and controlled as possible. Disposable surgeons gowns play a direct role in this by acting as a protective layer, helping reduce the possibility of contamination during operations.</p></div><div className="stats-box">{[{ num: "Surgical", label: "Protection" }, { num: "Germ", label: "Control" }, { num: "Single", label: "Use Design" }, { num: "India", label: "Wide Supply" }].map(({ num, label }) => <div key={label} className="stat-card"><p className="stat-num">{num}</p><p className="stat-label">{label}</p></div>)}</div></div></section>

      <section className="products-section"><div className="products-inner"><p className="section-label">Understanding the Product</p><h2 className="section-heading">What is a Disposable Surgeons Gown and Why is it Essential?</h2><div className="product-card card-hover"><div className="product-card-body"><p className="product-card-desc">A disposable surgeons gown is a protective garment used during surgery to help minimize the transfer of germs. It is worn by surgeons as part of standard protective practices in operating environments.</p><p className="product-card-desc">Its importance comes from its role in infection control. During surgery, even minimal contamination can affect outcomes. By acting as a barrier, the gown helps reduce direct exposure between the surgeon and the surgical environment, supporting safer procedures.</p></div></div></div></section>

      <section className="products-section"><div className="products-inner"><p className="section-label">Infection Control</p><h2 className="section-heading">How Disposable Surgeons Gowns Support Infection Control</h2><div className="product-card card-hover"><div className="product-card-body"><p className="product-card-desc">In surgical settings, controlling the spread of germs is a key priority. A disposable surgeons gown contributes to this by providing an additional protective layer that helps limit the transfer of contaminants.</p><p className="product-card-desc">This protection is especially important during procedures where maintaining a clean and controlled environment is critical. By reducing the risk of contamination, the gown supports better hygiene practices and safer surgical conditions.</p></div></div></div></section>

      <section className="features-section"><div className="features-inner"><p className="features-label">Product Highlights</p><h2 className="features-heading">Key Functional Benefits of Disposable Surgeons Gown</h2><p className="overview-text" style={{ textAlign: "center", maxWidth: "800px", margin: "0 auto 3rem" }}>The disposable surgeons gown is designed for practical use in surgical environments. Its primary function is to help prevent the transfer of germs while being worn during procedures.</p><div className="three-col">{[{ icon: "🛡️", title: "Protective Barrier", desc: "Helps reduce the transfer of germs between the surgeon and surgical environment." }, { icon: "🏥", title: "Surgical Use", desc: "Suitable for operating rooms and procedures where hygiene is essential." }, { icon: "🧼", title: "Infection Control", desc: "Supports clean and controlled conditions during medical procedures." }, { icon: "⚕️", title: "Practical Design", desc: "Designed for routine use as part of standard surgical protective wear." }, { icon: "♻️", title: "Disposable", desc: "Single-use nature supports consistent hygiene during operations." }, { icon: "⚡", title: "Easy to Use", desc: "Practical protective clothing for everyday surgical requirements." }].map(f => <div key={f.title} className="feature-card"><span className="feature-icon">{f.icon}</span><h3 className="feature-title">{f.title}</h3><p className="feature-desc">{f.desc}</p></div>)}</div></div></section>

      <section id="applications" className="applications-section"><div className="applications-inner"><p className="section-label">Where It&apos;s Used</p><h2 className="section-heading">Applications of Disposable Surgeons Gown</h2><p className="overview-text" style={{ textAlign: "center", maxWidth: "800px", margin: "0 auto 3rem" }}>Disposable surgeons gowns are used in operating rooms and medical environments where surgical procedures are carried out. They are worn by surgeons as part of routine protective practices to help reduce contamination risks.</p><div className="four-col">{APPLICATIONS.map(app => <div key={app.title} className="app-card card-hover"><span className="app-icon">{app.icon}</span><h3 className="app-title">{app.title}</h3><p className="app-desc">{app.desc}</p></div>)}</div></div></section>

      <section className="section"><div className="two-col"><div><p className="overview-label">Surgical Protection</p><h2 className="overview-heading">Why Disposable Surgeons Gowns Are Critical in Surgery</h2><p className="overview-text">In surgical environments, maintaining control over contamination is not optional—it is a necessity. Disposable surgeons gowns help support this by acting as a barrier that reduces the transfer of germs.</p><p className="overview-text-last">Their use contributes to maintaining a clean surgical field, supporting better procedural outcomes and reinforcing hygiene standards in healthcare environments.</p></div><div className="stats-box">{[{ num: "Clean", label: "Surgical Field" }, { num: "Germ", label: "Reduction" }, { num: "Controlled", label: "Conditions" }, { num: "Safe", label: "Procedures" }].map(({ num, label }) => <div key={label} className="stat-card"><p className="stat-num">{num}</p><p className="stat-label">{label}</p></div>)}</div></div></section>

      <section className="supplier-section"><div className="supplier-inner"><div><p className="supplier-label">Supplier in India</p><h2 className="supplier-heading">Disposable Surgeons Gown Supplier in India</h2><p className="supplier-text">Crown Healthcare Disposables is a reliable disposable surgeons gown manufacturer and supplier in India, supporting healthcare institutions with essential protective clothing. We focus on meeting the ongoing demand for products used in surgical environments where hygiene and infection control are critical.</p><p className="supplier-text-last">As a surgeons gown supplier, we aim to support customers with dependable disposable protective products that help maintain controlled and hygienic conditions during procedures.</p></div><div id="contact" className="contact-card"><h3 className="contact-title">Request a Quote</h3><div className="form-fields">{["Your Name", "Company / Organisation", "Email Address", "Phone Number"].map(ph => <input key={ph} placeholder={ph} className="form-input" />)}<textarea placeholder="Your Requirements" className="form-input" rows="3" /><button className="form-btn">Submit Enquiry →</button></div></div></div></section>

      <section className="products-section"><div className="products-inner"><p className="section-label">Our Commitment</p><h2 className="section-heading">Why Choose Crown Healthcare Disposables</h2><div className="product-card card-hover"><div className="product-card-body"><p className="product-card-desc">Choosing the right disposable surgeons gown manufacturer in India is important for healthcare providers that rely on consistent protective solutions. Crown Healthcare Disposables focuses on delivering products that align with real surgical requirements.</p><p className="product-card-desc">We aim to be a trusted manufacturing partner for businesses and healthcare providers seeking practical and reliable surgical protective wear.</p></div></div></div></section>

      <section id="faqs" className="faqs-section"><div className="faqs-inner"><p className="faqs-label">Got Questions?</p><h2 className="faqs-heading">Frequently Asked Questions</h2><div>{FAQS.map(faq => <FAQItem key={faq.q} {...faq} />)}</div></div></section>

      <section className="related-section"><div className="related-inner"><h2 className="related-heading">Related Products</h2><div className="related-scroll">{RELATED_PRODUCTS.map(product => <Link key={product.id} href={product.href} className="related-card-link"><div className="related-card"><div className="related-card-img"><img src={product.image} alt={product.name} className="related-img" /></div><div className="related-card-info"><h3 className="related-card-name">{product.name}</h3><span className="related-card-btn">View More</span></div></div></Link>)}</div></div></section>
    </>
  );
}
